### ISSUE TITLE
install command causes unexpected crash

### ISSUE THREAD

**Issue by ChrisTimperley** [ChrisTimperley/start_stack#14]
```
oot@up-board:~/start/hardware/work-2018-09-04_16-45-59# start-cli --archive ./genprog/image.tar.gz ./scenario.config 
usage: start [-h] [--debug] [--quiet] [--version] [--verbose]
             {build,install,analyze,coverage,localize,repair,snippets,transformations,validate,execute}
             ...
start: error: argument command: invalid choice: './genprog/image.tar.gz' (choose from 'build', 'install', 'analyze', 'coverage', 'localize', 'repair', 'snippets', 'transformations', 'validate', 'execute')
root@up-board:~/start/hardware/work-2018-09-04_16-45-59# start-cli install --archive ./genprog/image.tar.gz ./scenario.config 
INFO:start_cli.image:loaded scenario
INFO:start_cli.image:installing Docker image [christimperley/start:kleach-hw] for scenario [kleach-hw] from archive: ./genprog/image.tar.gz
DEBUG:start_image.install:installing Docker image for scenario [kleach-hw] from archive: ./genprog/image.tar.gz
DEBUG:start_image.install:failed to open archive: ./genprog/image.tar.gz
ERROR:start_cli.image:failed to install image from archive
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.5/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 913, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.5/http/client.py", line 882, in send
    self.sock.sendall(datablock)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by ChrisTimperley** [comment]
Install command is no longer used.
